---
development: &id003
  :active_school_levels:
    - "2"
    - "3"
    - "4"
  :active_grades:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  :theme: has
  :site_name: HAS Investigations
  :site_url: http://has.portal.concord.org
  :runnable_mime_type:
  :top_level_container_name: investigation
  :site_school: HAS Investigations-school
  :description: ""
  :site_district: HAS Investigations-district
  :help_email: apallant@concord.org
  :admin_email: aunger@concord.org
  :tiny_mce:
    :buttons1:
    - bold,italic,underline
    - sup,sub
    - bullist,numlist
    - link,image
    - pastext, pasteword,selectall
    - justifyleft,justifycenter,justifyright
    - code

  :default_admin_user:
    :first_name: Aaron
    :login: aunger
    :last_name: Unger
    :email: aunger@concord.org
  :states_and_provinces:
    - MA
  :use_adhoc_workgroups: true
test: *id003
production: *id003
staging: *id003
cucumber: *id003
