# This is an docker-compose overlay that publishes the mysql port.
# If you already have a mysql instance running locally on 3306 and you do not
# want to terminate it, edit the port mapping below with a different initial
# port. E.g. "3307:3306" will publish the mysql instance running in Docker to
# local port 3307.

# A convient way to overlay this file is to add a `.env` file with the contents:
#  COMPOSE_FILE=docker-compose.yml:docker/dev/docker-compose-publish-mysql-ports.yml
# You can also do it manually when you run docker-compose each time with
# docker-compose -f docker-compose.yml -f docker/dev/docker-compose-publish-mysql-port.yml
# if you are making changes to docker-compose.yml or this file it is useful to
# run `docker-compose config` which shows how the two files get merged together

version: '3'
services:
  mysql:
    ports:
      - "3306:3306"
