# IMPORTANT: This file was generated by Cucumber 0.4.4
# Edit at your own peril - it's recommended to regenerate this file
# in the future when you upgrade to a newer version of Cucumber.
# Consider adding your own code to a new file instead of editing this one.

# edited to integrate with spork
# 
# use 'spork cuc' in one terminal
# then 'cucumber ./features -drb' to run tests.
# See: 
#  http://github.com/bmabey/cucumber-tmbundle/
#  for info about how to set TM ENV variables to use spork.
#
# Sets up the Rails environment for Cucumber
ENV["RAILS_ENV"] ||= "cucumber"

require 'rubygems'
require 'spork'

Spork.prefork do

  require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')
  require 'cucumber/rails/world'
  require 'email_spec'
  require 'email_spec/cucumber'
  
  # If you set this to true, each scenario will run in a database transaction.
  # You can still turn off transactions on a per-scenario basis, simply tagging 
  # a feature or scenario with the @no-txn tag. 
  #
  # If you set this to false, transactions will be off for all scenarios,
  # regardless of whether you use @no-txn or not.
  #
  # Beware that turning transactions off will leave data in your database 
  # after each scenario, which can lead to hard-to-debug failures in 
  # subsequent scenarios. If you do this, we recommend you create a Before
  # block that will explicitly put your database in a known state.
  Cucumber::Rails::World.use_transactional_fixtures = true

  # If you set this to false, any error raised from within your app will bubble 
  # up to your step definition and out to cucumber unless you catch it somewhere
  # on the way. You can make Rails rescue errors and render error pages on a
  # per-scenario basis by tagging a scenario or feature with the @allow-rescue tag.
  #
  # If you set this to true, Rails will rescue all errors and render error
  # pages, more or less in the same way your application would behave in the
  # default production environment. It's not recommended to do this for all
  # of your scenarios, as this makes it hard to discover errors in your application.
  ActionController::Base.allow_rescue = false

  require 'cucumber'
  # Comment out the next line if you don't want Cucumber Unicode support
  require 'cucumber/formatter/unicode'
  require 'cucumber/webrat/element_locator' # Lets you do table.diff!(element_at('#my_table_or_dl_or_ul_or_ol').to_table)
  require 'cucumber/rails/rspec'

  require 'webrat'
  require 'webrat/core/matchers' 
  Webrat.configure do |config|
    config.mode = :rails
    config.open_error_files = false # Set to true if you want error pages to pop up in the browser
  end

  APP_CONFIG[:theme] = 'default' #lots of tests seem to be broken if we try to use another theme
  
  # use factory girl:
  require 'factory_girl'
  Dir.glob(File.join(File.dirname(__FILE__), '../factories/*.rb')).each {|f| require f }
  
  # This code used to live in factories/zz_default_data.rb.
  # It boots the cucmber environement with a default project.
  # required by application_controller.rb
  puts "Loading default data set required for application_controller.rb to run ...."
  anon =  Factory.next :anonymous_user
  admin = Factory.next :admin_user 
  device_config = Factory.create(:probe_device_config)
  versioned_jnlp = Factory(:maven_jnlp_versioned_jnlp)
  school = Factory(:portal_school)
  domain = Factory(:rigse_domain)
  grade = Factory(:portal_grade)
  Admin::Project.create_or_update_default_project_from_settings_yml
  puts "done."
  
  # Make visible for testing
  include AuthenticatedSystem
  ApplicationController.send(:public, :logged_in?, :current_user, :authorized?)
end

Spork.each_run do
  # This code will be run each time you run your specs.
  
end
