#!/usr/bin/env ruby

prototype_rails_methods = [
  "remote_form_for",
  "visual_effect",
  "link_to_remote",
  "link_to_function",
  "sortable_element",
  "drop_receiving_element",
  "button_to_remote",
  "draggable_element",
  "observe_form",
  "remote_function",
]

helpers_that_use_prototype_rails = [
  "wrap_edit_link_around_content",
  "toggle_all",
  "toggle_more",
  "remote_link_button",
  "function_link_button",
  "remove_link",
  "student_add_dropdown",
  "teacher_add_dropdown",
  "edit_button_for", # uses remote_link_button
  "delete_button_for", # uses remote_link_button
  "show_menu_for", # uses edit_button_for and delete_button_for
]

def print_md_table(title, headers, rows)
  puts "## #{title}"
  puts ''

  # add row index colum
  # we aren't using unshift so we don't modify the input arguments
  headers = [""] + headers
  rows = rows.map.with_index do |row, index|
    [(index+1).to_s] + row
  end

  padded_headers = headers.map.with_index do |header, index|
    max_cell_length = rows.map{|row| row[index].length}.max
    header.ljust(max_cell_length)
  end
  puts "| #{padded_headers.join(" | ")} |"
  puts "| #{padded_headers.map{|h| "-"*h.length}.join(" | ")} |"
  rows.each do |row|
    padded_cells = row.map.with_index{|item, index| item.ljust(padded_headers[index].length)}
    puts "| #{padded_cells.join(" | ")} |"
  end
  puts ''
end

def md_code(code)
  # escape the | since it is picked up by the md table parser
  escaped = code.gsub("|","\\|")
  "`#{escaped.strip}`"
end

def grep_files(directory, strings, function=false, prefix='', suffix='')
  original_dir = Dir.pwd
  Dir.chdir directory
  results = []
  last_def = ""
  Dir['**/*'].sort.each do |file_name|
    next unless File.file?(file_name)
    File.open file_name do |file|
      file.each_with_index do |line,line_number|
        if line.match("def ")
          last_def = line.strip
        end
        strings.each do |method|
          # don't match the method if it is preceded by a _
          if line.match("#{prefix}(?<![_\"])#{method}(?![_\"])#{suffix}")
            if function
              results << ["#{file_name}:#{line_number+1}", method, last_def, md_code(line)]
            else
              results << ["#{file_name}:#{line_number+1}", method, md_code(line)]
            end
          end
        end
      end
    end
  end
  Dir.chdir original_dir
  results
end

puts "# Prototype Rails Usage"
puts ""
puts "This was generated by"
puts "```"
puts "cd rails/script"
puts "ruby prototype-rails-usage.rb > ../../docs/prototype-rails-usage.md"
puts "```"

# This adds an additional table just linksing views that directly use
# the prototype rails functions
# results = grep_files("../app/views", prototype_rails_methods)
# print_md_table("Views directly using prototype-rails",
#   ["file", "method", "line" ],
#   results
# )

results = grep_files("../app/helpers", prototype_rails_methods, true)
print_md_table("Helpers directly using prototype-rails",
  ["file", "helper", "function", "line" ],
  results
)

# use a negative look behind to skip the actual function definitions themseleves
results = grep_files("../app/helpers", helpers_that_use_prototype_rails, true, "(?<!def )")
print_md_table("Helpers using helpers which use prototype-rails",
  ["file", "helper", "function", "line" ],
  results
)

results = grep_files("../app/views", prototype_rails_methods + helpers_that_use_prototype_rails)
print_md_table("Views that use prototype-rails or a helper that uses it",
  ["file", "helper", "line" ],
  results
)

summary = results
  .group_by{|result| result[0].split(":")[0]}
  .map{|key,value| [key, ""]}

# generate the solution hash which is then embedded back in this file
# puts '{'
# summary_pretty_hash_keys = summary.map{|row| "\"#{row[0]}\"=>"}
# # key_width = summary_pretty_hash_keys.map{|key| key.length}.max
# summary.map{|row| row[0]}.each do |key|
#   puts "\"#{key}\"=>{"
#   puts "  references: \"\","
#   puts "  solution:   \"\","
#   puts "  rational:   \"\","
#   puts "  story:      \"\"},"
# end
# puts '}'

# this table was generated using the snippet aboves intended to be used
solutions_hash = {
"admin/clients/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/commons_licenses/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/external_reports/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/projects/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/projects/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/settings/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/settings/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/settings/_show_for_managers.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/tags/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"admin/tags/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"author_notes/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"author_notes/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/blobs/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/blobs/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/bundle_contents/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/bundle_loggers/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/bundle_loggers/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/console_contents/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/console_loggers/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"dataservice/console_loggers/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"embeddable/image_questions/_remote_form.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/image_questions/",
  rational:   "no longer needed",
  story:      ""},
"embeddable/image_questions/_show.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/image_questions/",
  rational:   "no longer needed",
  story:      ""},
"embeddable/multiple_choices/_edit_choice.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/multiple_choices/",
  rational:   "no longer needed",
  story:      ""},
"embeddable/multiple_choices/_remote_form.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/multiple_choices/",
  rational:   "no longer needed",
  story:      ""},
"embeddable/multiple_choices/_show.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/multiple_choices/",
  rational:   "no longer needed",
  story:      ""},
"embeddable/open_responses/_remote_form.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/open_responses/",
  rational:   "no longer needed",
  story:      ""},
"embeddable/open_responses/_show.html.haml"=>{
  references: "",
  solution:   "remove all embeddable/open_responses/",
  rational:   "no longer needed",
  story:      ""},
"external_activities/_basic_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"external_activities/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"external_activities/_runnable_list.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"external_activities/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"external_activities/create.js.rjs"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"external_activities/index.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"images/index.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"interactives/index.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"materials_collections/_materials_in_collection.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"materials_collections/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"materials_collections/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/bookmarks/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/bookmarks/generic_bookmark/_button.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/bookmarks/padlet_bookmark/_button.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/clazzes/_form_student_roster.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/clazzes/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/clazzes/_remote_form_student_roster.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/clazzes/edit_offerings.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/districts/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/districts/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/grade_levels/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/grade_levels/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/grades/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/grades/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/learners/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/offerings/_list_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/schools/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/schools/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/student_clazzes/destroy.js.rjs"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/students/_add_edit_list_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/students/_current_student_list_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/students/_list_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/students/_move.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/students/_register.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/students/_table_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/teachers/_list_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/teachers/_list_for_clazz_setup.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/teachers/_table_for_clazz.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"portal/teachers/_table_for_clazz_setup.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"search/_material_unassigned_clazzes.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"search/_material_unassigned_collections.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_accordion_nav.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_activity_header.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_activity_trail.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_collection_menu.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_embeddable_container.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_external_activity_header.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_general_accordion_nav.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_notes_menu.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_offering_for_teacher.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_page_header.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_runnable.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_runnables_listing.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"shared/_section_header.html.haml"=>{
  references: "",
  solution:   "remove",
  rational:   "no references",
  story:      ""},
"teacher_notes/_remote_form.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"teacher_notes/_show.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
"users/index.html.haml"=>{
  references: "",
  solution:   "",
  rational:   "",
  story:      ""},
}

solutions = summary.map do |row|
  solution = solutions_hash[row[0]]
  [row[0],
   solution[:references],
   solution[:solution],
   solution[:rational],
   # it'd be nice to parse and format these URLs better
   solution[:story]
  ]
end
print_md_table("Summary of views using prototype-rails",
  ["file", "References", "Solution", "Rational", "Story"],
  solutions
)
