#!/bin/bash
set -ev

cp config/database.travis.yml config/database.yml
cp config/app_environment_variables.sample.rb config/app_environment_variables.rb
cp config/settings.sample.yml config/settings.yml
mysql -e 'create database rigse_test;'
mysql -e 'create database rigse_features;'
mysql -uroot -e 'GRANT ALL ON rigse_test.* TO 'travis'@'localhost';'
mysql -uroot -e 'GRANT ALL ON rigse_features.* TO 'travis'@'localhost';'
bundle exec spring binstub --all
# Run all migrations to make sure they work
# Because we have multiple workers this isn't the most efficient way to do this
# The migrations are going to be run on the RAILS_ENV database, and then
# the pepare tasks are going to blow them away and load the schema
# The migrations aren't currently working from scratch on travis,
# so this is disabled for now
# ./bin/rake db:migrate
./bin/rake db:test:prepare
./bin/rake db:feature_test:prepare
RAILS_GROUPS=assets ./bin/rake assets:precompile:all
RAILS_ENV=test ./bin/rake sunspot:solr:start &
sleep 10 # give SOLR some time to start and init
