FROM concordconsortium/docker-rails-base-ruby-2.2.6:1.1

#
# Install some basic dev tools
#
RUN apt-get update && apt-get install -y vim xvfb firefox-esr

#
# Install wait-for-it to support docker-volume-sync
WORKDIR /usr/local/bin
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/db049716e42767d39961e95dd9696103dca813f1/wait-for-it.sh && \
    chmod +x wait-for-it.sh

ENV APP_HOME /rigse
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# use a mounted volume so the gems don't need to be rebundled each time
ENV BUNDLE_PATH /bundle

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=2 \
  BUNDLE_PATH=/bundle

ENV RAILS_ENV=development

EXPOSE 3000

CMD rails s -b 0.0.0.0
