---
development: &id003
  :active_school_levels:
    - "2"
    - "3"
    - "4"
  :active_grades:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  :theme: default
  :site_name: DEFAULT Investigations
  :site_url: http://localhost:3000
  :runnables_use: otrunk_jnlp
  :runnable_mime_type:
  :top_level_container_name: investigation
  :site_school: DEFAULT Investigations-school
  :description: ""
  :site_district: DEFAULT Investigations-district
  :help_email: default-investigations@concord.org
  :default_admin_user:
    :first_name: Stephen
    :login: stephen
    :last_name: Bannasch
    :email: stephen.bannasch@gmail.com
  :states_and_provinces:
    - RI

test: *id003
staging: *id003
cucumber: *id003

production:
  :active_school_levels:
    - "2"
    - "3"
    - "4"
  :active_grades:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  :theme: itsi-learn
  :site_name: DEFAULT Investigations
  :site_url: http://localhost:3000
  :runnables_use: otrunk_jnlp
  :runnable_mime_type:
  :top_level_container_name: investigation
  :site_school: DEFAULT Investigations-school
  :description: ""
  :site_district: DEFAULT Investigations-district
  :help_email: default-investigations@concord.org
  :default_admin_user:
    :first_name: Stephen
    :login: stephen
    :last_name: Bannasch
    :email: stephen.bannasch@gmail.com
  :states_and_provinces:
    - RI
