development: &non_production_settings
  :site_name: Rails Portal (development)
  :site_url: <%= ENV["SITE_URL"] || 'http://localhost:3000' %>
  :authoring_site_url: //authoring.staging.concord.org
  :codap_url: http://codap.concord.org/releases/latest/
  :log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
  :description: ""
  :default_admin_user: &default_admin_user
    :login: admin
    :email: admin@concord.org
    :first_name: Admin
    :last_name: Admin
  :site_district: Rails Portal-district
  :site_school: Rails Portal-school
  :states_and_provinces: &states_and_provinces
    - MA
  :active_school_levels: &active_school_levels
    - "2"
    - "3"
    - "4"
  :active_grades: &active_grades
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "Higher Ed"
  :theme: <%= ENV["THEME"] || 'learn' %>
  :help_email: rails-portal@concord.org
  :dont_sanitize_xhtml: true
  :tiny_mce:
    :buttons1:
      - bold,italic,underline
      - formatselect
      - styleselect
      - sup,sub
      - bullist,numlist
      - link,image
      - pastext, pasteword,selectall
      - justifyleft,justifycenter,justifyright
      - code
  :pepper: 7ed5d246-cc1a-11e1-81dd-0800270eb79b
  :password_for_default_users: password

test: &test
  <<: *non_production_settings
  :password_for_default_users: password

cucumber: *test
feature_test: *test

staging:
  :password_for_default_users: secret
  :site_name: Rails Portal (staging)
  :authoring_site_url: //authoring.staging.concord.org
  :codap_url: http://codap.concord.org/releases/latest/
  :log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
  :site_url: http://rails-portal.staging.concord.org
  :description: ""
  :default_admin_user: *default_admin_user
  :states_and_provinces: *states_and_provinces
  :active_school_levels: *active_school_levels
  :active_grades: *active_grades
  :site_district: Rails Portal-district
  :site_school: Rails Portal-school
  :help_email: rails-portal@concord.org
  :dont_sanitize_xhtml: true
  :tiny_mce:
    :buttons1:
      - bold,italic,underline
      - sup,sub
      - bullist,numlist
      - link,image
      - pastext, pasteword,selectall
      - justifyleft,justifycenter,justifyright
      - code
  :pepper: 7ed5d246-cc1a-11e1-81dd-0800270eb79b
  :theme: <%= ENV["THEME"] || 'learn' %>

production:
  # :site_name: Rails Portal
  # :site_url: http://rails-portal.concord.org
  # :authoring_site_url: //authoring.staging.concord.org
  # :codap_url: http://codap.concord.org/releases/latest/
  # :log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
  # :description: ""
  # :default_admin_user: *default_admin_user
  # :states_and_provinces: *states_and_provinces
  # :active_school_levels: *active_school_levels
  # :active_grades: *active_grades
  # :site_district: Rails Portal-district
  # :site_school: Rails Portal-school
  # :help_email: rails-portal@concord.org
  # :admin_email: npaessel@concord.org
  # :allow_drafts_in_assignments: false
  # :dont_sanitize_xhtml: true
  # :tiny_mce:
  #   :buttons1:
  #     - bold,italic,underline
  #     - sup,sub
  #     - bullist,numlist
  #     - link,image
  #     - pastext, pasteword,selectall
  #     - justifyleft,justifycenter,justifyright
  #     - code
  # :pepper: 7ed5d246-cc1a-11e1-81dd-0800270eb79b
  # :theme: <%= ENV["THEME"] || 'learn' %>

  password_for_default_users: ccpassword
  site_name: <%= ENV["SITE_NAME"] || 'Rails Portal' %>
  site_url: <%= ENV["SITE_URL"] || 'http://learn.concord.org' %>
  authoring_site_url: <%= ENV["AUTHORING_SITE_URL"] || '//authoring.staging.concord.org' %>
  theme: <%= ENV["THEME"] || 'learn' %>
  admin_email: <%= ENV["ADMIN_EMAIL"] || 'npaessel@concord.org' %>
  help_email: <%= ENV["HELP_EMAIL"] || 'rails-portal@concord.org' %>
  use_adhoc_workgroups: true
  site_school: <%= ENV["SITE_NAME"] || 'site_name' %>-school
  site_district: <%= ENV["SITE_NAME"] || 'site_district' %>-district
  active_school_levels:
    - "2"
    - "3"
    - "4"
  active_grades:
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "Higher Ed"
  tiny_mce:
    buttons1:
      - bold,italic,underline
      - sup,sub
      - bullist,numlist
      - link,image
      - pastext, pasteword,selectall
      - code
  dont_sanitize_xhtml: false
  default_admin_user:
    first_name: Noah
    login: knowuh
    last_name: Paessel
    email: npaessel@concord.org
  states_and_provinces: all
  runnable_mime_type:
  top_level_container_name: <%= ENV["TOP_LEVEL_CONTAINER_NAME"] || 'top-level-container-name' %>
  pepper: <%= ENV["SITE_KEY"] || '7ed5d246-cc1a-11e1-81dd-0800270eb79b' %>
  codap_url: http://codap.concord.org/releases/latest/
  log_manager_data_interactive_url: //cc-log-manager.herokuapp.com/di
