production:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || 'localhost' %>
    port: <%= ENV['SOLR_PORT'] || 8983 %>
    log_level: WARNING
    path: /solr/production
    solr_home: <%= Rails.root %>/solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= ENV['SOLR_HOST'] || 'localhost' %>
    port: <%= ENV['SOLR_PORT'] || 8982 %>
    log_level: INFO
    path: /solr/development
    solr_home: <%= Rails.root %>/solr

test: &TEST
  solr:
    hostname:   <%= ENV['TEST_SOLR_HOST'] || 'localhost' %>
    port:       <%= ENV['TEST_SOLR_PORT'] || 8981 %>
    log_level: WARNING
    path: /solr/test
    solr_home: <%= Rails.root %>/solr
    auto_commit_after_request: false
cucumber:
  <<: *TEST
