---
development: &id003
  :active_school_levels:
    - "2"
    - "3"
    - "4"
  :active_grades:
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
  :use_gse: false
  :help_email: skim@concord.org
  :theme: smartgraphs
  :site_school: SmartGraphs School
  :description: ""
  :site_district: SmartGraphs District
  :site_name: SmartGraphs
  :site_url: http://smartgraphs.dev.concord.org
  :runnable_mime_type: run_external_html
  :default_maven_jnlp: 
  :runnables_use: browser
  :default_admin_user:
    :first_name: Aaron
    :last_name: Unger
    :login: aunger
    :email: aunger@concord.org
  :states_and_provinces:
  - MA
test: *id003
production: *id003
staging: *id003
cucumber: *id003
