version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "report-service-demo-report"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fugzou65cjxx"
s3_prefix = "report-service-demo-report"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
