AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  report-service-demo-report
  Sample SAM Template for report-service-demo-report

Parameters:
  JwtHmacSecret:
    Type: String
    Description: Secret to verify request
    # Default: [for development, the JwtHmacSecret can be pasted here, BUT SHOULD NEVER BE COMMITTED]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        JWT_HMAC_SECRET: !Ref JwtHmacSecret

Resources:
  DemoReportFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: report-demo/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Report:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /report-demo
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ReportApi:
    Description: "API Gateway endpoint URL for demo report function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/report-demo/"
