class CreateNces06Tables < ActiveRecord::Migration

  def self.up
    create_table :nces06_districts do |t|
      t.text :LEAID
      t.text :FIPST
      t.text :STID
      t.text :NAME
      t.text :PHONE
      t.text :MSTREE
      t.text :MCITY
      t.text :MSTATE
      t.text :MZIP
      t.text :MZIP4
      t.text :LSTREE
      t.text :LCITY
      t.text :LSTATE
      t.text :LZIP
      t.text :LZIP4
      t.text :TYPE
      t.text :UNION
      t.text :CONUM
      t.text :CONAME
      t.text :CSA
      t.text :CBSA
      t.text :METMIC
      t.text :MSC
      t.text :ULOCAL
      t.text :CDCODE
      t.integer :LATCOD
      t.integer :LONCOD
      t.text :BOUND
      t.text :GSLO
      t.text :GSHI
      t.text :AGCHRT
      t.integer :SCH
      t.integer :TEACH
      t.integer :UG
      t.integer :PK12
      t.integer :MEMBER
      t.integer :MIGRNT
      t.integer :SPECED
      t.integer :ELL
      t.integer :PKTCH
      t.integer :KGTCH
      t.integer :ELMTCH
      t.integer :SECTCH
      t.integer :UGTCH
      t.integer :TOTTCH
      t.integer :AIDES
      t.integer :CORSUP
      t.integer :ELMGUI
      t.integer :SECGUI
      t.integer :TOTGUI
      t.integer :LIBSPE
      t.integer :LIBSUP
      t.integer :LEAADM
      t.integer :LEASUP
      t.integer :SCHADM
      t.integer :SCHSUP
      t.integer :STUSUP
      t.integer :OTHSUP
      t.text :IGSLO
      t.text :IGSHI
      t.text :ISCH
      t.text :ITEACH
      t.text :IUG
      t.text :IPK12
      t.text :IMEMB
      t.text :IMIGRN
      t.text :ISPEC
      t.text :IELL
      t.text :IPKTCH
      t.text :IKGTCH
      t.text :IELTCH
      t.text :ISETCH
      t.text :IUGTCH
      t.text :ITOTCH
      t.text :IAIDES
      t.text :ICOSUP
      t.text :IELGUI
      t.text :ISEGUI
      t.text :ITOGUI
      t.text :ILISPE
      t.text :ILISUP
      t.text :ILEADM
      t.text :ILESUP
      t.text :ISCADM
      t.text :ISCSUP
      t.text :ISTSUP
      t.text :IOTSUP
    end
    create_table :nces06_schools do |t|
      t.text :NCESSCH
      t.text :FIPST
      t.text :LEAID
      t.text :SCHNO
      t.text :STID
      t.text :SEASCH
      t.text :LEANM
      t.text :SCHNAM
      t.text :PHONE
      t.text :MSTREE
      t.text :MCITY
      t.text :MSTATE
      t.text :MZIP
      t.text :MZIP4
      t.text :LSTREE
      t.text :LCITY
      t.text :LSTATE
      t.text :LZIP
      t.text :LZIP4
      t.text :TYPE
      t.text :STATUS
      t.text :ULOCAL
      t.text :LATCOD
      t.text :LONCOD
      t.text :CDCODE
      t.text :CONUM
      t.text :CONAME
      t.integer :FTE
      t.text :GSLO
      t.text :GSHI
      t.text :LEVEL
      t.text :TITLEI
      t.text :STITLI
      t.text :MAGNET
      t.text :CHARTR
      t.text :SHARED
      t.integer :FRELCH
      t.integer :REDLCH
      t.integer :TOTFRL
      t.integer :MIGRNT
      t.integer :PK
      t.integer :AMPKM
      t.integer :AMPKF
      t.integer :AMPKU
      t.integer :ASPKM
      t.integer :ASPKF
      t.integer :ASPKU
      t.integer :HIPKM
      t.integer :HIPKF
      t.integer :HIPKU
      t.integer :BLPKM
      t.integer :BLPKF
      t.integer :BLPKU
      t.integer :WHPKM
      t.integer :WHPKF
      t.integer :WHPKU
      t.integer :KG
      t.integer :AMKGM
      t.integer :AMKGF
      t.integer :AMKGU
      t.integer :ASKGM
      t.integer :ASKGF
      t.integer :ASKGU
      t.integer :HIKGM
      t.integer :HIKGF
      t.integer :HIKGU
      t.integer :BLKGM
      t.integer :BLKGF
      t.integer :BLKGU
      t.integer :WHKGM
      t.integer :WHKGF
      t.integer :WHKGU
      t.integer :G01
      t.integer :AM01M
      t.integer :AM01F
      t.integer :AM01U
      t.integer :AS01M
      t.integer :AS01F
      t.integer :AS01U
      t.integer :HI01M
      t.integer :HI01F
      t.integer :HI01U
      t.integer :BL01M
      t.integer :BL01F
      t.integer :BL01U
      t.integer :WH01M
      t.integer :WH01F
      t.integer :WH01U
      t.integer :G02
      t.integer :AM02M
      t.integer :AM02F
      t.integer :AM02U
      t.integer :AS02M
      t.integer :AS02F
      t.integer :AS02U
      t.integer :HI02M
      t.integer :HI02F
      t.integer :HI02U
      t.integer :BL02M
      t.integer :BL02F
      t.integer :BL02U
      t.integer :WH02M
      t.integer :WH02F
      t.integer :WH02U
      t.integer :G03
      t.integer :AM03M
      t.integer :AM03F
      t.integer :AM03U
      t.integer :AS03M
      t.integer :AS03F
      t.integer :AS03U
      t.integer :HI03M
      t.integer :HI03F
      t.integer :HI03U
      t.integer :BL03M
      t.integer :BL03F
      t.integer :BL03U
      t.integer :WH03M
      t.integer :WH03F
      t.integer :WH03U
      t.integer :G04
      t.integer :AM04M
      t.integer :AM04F
      t.integer :AM04U
      t.integer :AS04M
      t.integer :AS04F
      t.integer :AS04U
      t.integer :HI04M
      t.integer :HI04F
      t.integer :HI04U
      t.integer :BL04M
      t.integer :BL04F
      t.integer :BL04U
      t.integer :WH04M
      t.integer :WH04F
      t.integer :WH04U
      t.integer :G05
      t.integer :AM05M
      t.integer :AM05F
      t.integer :AM05U
      t.integer :AS05M
      t.integer :AS05F
      t.integer :AS05U
      t.integer :HI05M
      t.integer :HI05F
      t.integer :HI05U
      t.integer :BL05M
      t.integer :BL05F
      t.integer :BL05U
      t.integer :WH05M
      t.integer :WH05F
      t.integer :WH05U
      t.integer :G06
      t.integer :AM06M
      t.integer :AM06F
      t.integer :AM06U
      t.integer :AS06M
      t.integer :AS06F
      t.integer :AS06U
      t.integer :HI06M
      t.integer :HI06F
      t.integer :HI06U
      t.integer :BL06M
      t.integer :BL06F
      t.integer :BL06U
      t.integer :WH06M
      t.integer :WH06F
      t.integer :WH06U
      t.integer :G07
      t.integer :AM07M
      t.integer :AM07F
      t.integer :AM07U
      t.integer :AS07M
      t.integer :AS07F
      t.integer :AS07U
      t.integer :HI07M
      t.integer :HI07F
      t.integer :HI07U
      t.integer :BL07M
      t.integer :BL07F
      t.integer :BL07U
      t.integer :WH07M
      t.integer :WH07F
      t.integer :WH07U
      t.integer :G08
      t.integer :AM08M
      t.integer :AM08F
      t.integer :AM08U
      t.integer :AS08M
      t.integer :AS08F
      t.integer :AS08U
      t.integer :HI08M
      t.integer :HI08F
      t.integer :HI08U
      t.integer :BL08M
      t.integer :BL08F
      t.integer :BL08U
      t.integer :WH08M
      t.integer :WH08F
      t.integer :WH08U
      t.integer :G09
      t.integer :AM09M
      t.integer :AM09F
      t.integer :AM09U
      t.integer :AS09M
      t.integer :AS09F
      t.integer :AS09U
      t.integer :HI09M
      t.integer :HI09F
      t.integer :HI09U
      t.integer :BL09M
      t.integer :BL09F
      t.integer :BL09U
      t.integer :WH09M
      t.integer :WH09F
      t.integer :WH09U
      t.integer :G10
      t.integer :AM10M
      t.integer :AM10F
      t.integer :AM10U
      t.integer :AS10M
      t.integer :AS10F
      t.integer :AS10U
      t.integer :HI10M
      t.integer :HI10F
      t.integer :HI10U
      t.integer :BL10M
      t.integer :BL10F
      t.integer :BL10U
      t.integer :WH10M
      t.integer :WH10F
      t.integer :WH10U
      t.integer :G11
      t.integer :AM11M
      t.integer :AM11F
      t.integer :AM11U
      t.integer :AS11M
      t.integer :AS11F
      t.integer :AS11U
      t.integer :HI11M
      t.integer :HI11F
      t.integer :HI11U
      t.integer :BL11M
      t.integer :BL11F
      t.integer :BL11U
      t.integer :WH11M
      t.integer :WH11F
      t.integer :WH11U
      t.integer :G12
      t.integer :AM12M
      t.integer :AM12F
      t.integer :AM12U
      t.integer :AS12M
      t.integer :AS12F
      t.integer :AS12U
      t.integer :HI12M
      t.integer :HI12F
      t.integer :HI12U
      t.integer :BL12M
      t.integer :BL12F
      t.integer :BL12U
      t.integer :WH12M
      t.integer :WH12F
      t.integer :WH12U
      t.integer :UG
      t.integer :AMUGM
      t.integer :AMUGF
      t.integer :AMUGU
      t.integer :ASUGM
      t.integer :ASUGF
      t.integer :ASUGU
      t.integer :HIUGM
      t.integer :HIUGF
      t.integer :HIUGU
      t.integer :BLUGM
      t.integer :BLUGF
      t.integer :BLUGU
      t.integer :WHUGM
      t.integer :WHUGF
      t.integer :WHUGU
      t.integer :MEMBER
      t.integer :AM
      t.integer :AMALM
      t.integer :AMALF
      t.integer :AMALU
      t.integer :ASIAN
      t.integer :ASALM
      t.integer :ASALF
      t.integer :ASALU
      t.integer :HISP
      t.integer :HIALM
      t.integer :HIALF
      t.integer :HIALU
      t.integer :BLACK
      t.integer :BLALM
      t.integer :BLALF
      t.integer :BLALU
      t.integer :WHITE
      t.integer :WHALM
      t.integer :WHALF
      t.integer :WHALU
      t.integer :TOTETH
      t.integer :PUPTCH
      t.integer :TOTGRD
      t.text :IFTE
      t.text :IGSLO
      t.text :IGSHI
      t.text :ITITLI
      t.text :ISTITL
      t.text :IMAGNE
      t.text :ICHART
      t.text :ISHARE
      t.text :IFRELC
      t.text :IREDLC
      t.text :ITOTFR
      t.text :IMIGRN
      t.text :IPK
      t.text :IAMPKM
      t.text :IAMPKF
      t.text :IAMPKU
      t.text :IASPKM
      t.text :IASPKF
      t.text :IASPKU
      t.text :IHIPKM
      t.text :IHIPKF
      t.text :IHIPKU
      t.text :IBLPKM
      t.text :IBLPKF
      t.text :IBLPKU
      t.text :IWHPKM
      t.text :IWHPKF
      t.text :IWHPKU
      t.text :IKG
      t.text :IAMKGM
      t.text :IAMKGF
      t.text :IAMKGU
      t.text :IASKGM
      t.text :IASKGF
      t.text :IASKGU
      t.text :IHIKGM
      t.text :IHIKGF
      t.text :IHIKGU
      t.text :IBLKGM
      t.text :IBLKGF
      t.text :IBLKGU
      t.text :IWHKGM
      t.text :IWHKGF
      t.text :IWHKGU
      t.text :IG01
      t.text :IAM01M
      t.text :IAM01F
      t.text :IAM01U
      t.text :IAS01M
      t.text :IAS01F
      t.text :IAS01U
      t.text :IHI01M
      t.text :IHI01F
      t.text :IHI01U
      t.text :IBL01M
      t.text :IBL01F
      t.text :IBL01U
      t.text :IWH01M
      t.text :IWH01F
      t.text :IWH01U
      t.text :IG02
      t.text :IAM02M
      t.text :IAM02F
      t.text :IAM02U
      t.text :IAS02M
      t.text :IAS02F
      t.text :IAS02U
      t.text :IHI02M
      t.text :IHI02F
      t.text :IHI02U
      t.text :IBL02M
      t.text :IBL02F
      t.text :IBL02U
      t.text :IWH02M
      t.text :IWH02F
      t.text :IWH02U
      t.text :IG03
      t.text :IAM03M
      t.text :IAM03F
      t.text :IAM03U
      t.text :IAS03M
      t.text :IAS03F
      t.text :IAS03U
      t.text :IHI03M
      t.text :IHI03F
      t.text :IHI03U
      t.text :IBL03M
      t.text :IBL03F
      t.text :IBL03U
      t.text :IWH03M
      t.text :IWH03F
      t.text :IWH03U
      t.text :IG04
      t.text :IAM04M
      t.text :IAM04F
      t.text :IAM04U
      t.text :IAS04M
      t.text :IAS04F
      t.text :IAS04U
      t.text :IHI04M
      t.text :IHI04F
      t.text :IHI04U
      t.text :IBL04M
      t.text :IBL04F
      t.text :IBL04U
      t.text :IWH04M
      t.text :IWH04F
      t.text :IWH04U
      t.text :IG05
      t.text :IAM05M
      t.text :IAM05F
      t.text :IAM05U
      t.text :IAS05M
      t.text :IAS05F
      t.text :IAS05U
      t.text :IHI05M
      t.text :IHI05F
      t.text :IHI05U
      t.text :IBL05M
      t.text :IBL05F
      t.text :IBL05U
      t.text :IWH05M
      t.text :IWH05F
      t.text :IWH05U
      t.text :IG06
      t.text :IAM06M
      t.text :IAM06F
      t.text :IAM06U
      t.text :IAS06M
      t.text :IAS06F
      t.text :IAS06U
      t.text :IHI06M
      t.text :IHI06F
      t.text :IHI06U
      t.text :IBL06M
      t.text :IBL06F
      t.text :IBL06U
      t.text :IWH06M
      t.text :IWH06F
      t.text :IWH06U
      t.text :IG07
      t.text :IAM07M
      t.text :IAM07F
      t.text :IAM07U
      t.text :IAS07M
      t.text :IAS07F
      t.text :IAS07U
      t.text :IHI07M
      t.text :IHI07F
      t.text :IHI07U
      t.text :IBL07M
      t.text :IBL07F
      t.text :IBL07U
      t.text :IWH07M
      t.text :IWH07F
      t.text :IWH07U
      t.text :IG08
      t.text :IAM08M
      t.text :IAM08F
      t.text :IAM08U
      t.text :IAS08M
      t.text :IAS08F
      t.text :IAS08U
      t.text :IHI08M
      t.text :IHI08F
      t.text :IHI08U
      t.text :IBL08M
      t.text :IBL08F
      t.text :IBL08U
      t.text :IWH08M
      t.text :IWH08F
      t.text :IWH08U
      t.text :IG09
      t.text :IAM09M
      t.text :IAM09F
      t.text :IAM09U
      t.text :IAS09M
      t.text :IAS09F
      t.text :IAS09U
      t.text :IHI09M
      t.text :IHI09F
      t.text :IHI09U
      t.text :IBL09M
      t.text :IBL09F
      t.text :IBL09U
      t.text :IWH09M
      t.text :IWH09F
      t.text :IWH09U
      t.text :IG10
      t.text :IAM10M
      t.text :IAM10F
      t.text :IAM10U
      t.text :IAS10M
      t.text :IAS10F
      t.text :IAS10U
      t.text :IHI10M
      t.text :IHI10F
      t.text :IHI10U
      t.text :IBL10M
      t.text :IBL10F
      t.text :IBL10U
      t.text :IWH10M
      t.text :IWH10F
      t.text :IWH10U
      t.text :IG11
      t.text :IAM11M
      t.text :IAM11F
      t.text :IAM11U
      t.text :IAS11M
      t.text :IAS11F
      t.text :IAS11U
      t.text :IHI11M
      t.text :IHI11F
      t.text :IHI11U
      t.text :IBL11M
      t.text :IBL11F
      t.text :IBL11U
      t.text :IWH11M
      t.text :IWH11F
      t.text :IWH11U
      t.text :IG12
      t.text :IAM12M
      t.text :IAM12F
      t.text :IAM12U
      t.text :IAS12M
      t.text :IAS12F
      t.text :IAS12U
      t.text :IHI12M
      t.text :IHI12F
      t.text :IHI12U
      t.text :IBL12M
      t.text :IBL12F
      t.text :IBL12U
      t.text :IWH12M
      t.text :IWH12F
      t.text :IWH12U
      t.text :IUG
      t.text :IAMUGM
      t.text :IAMUGF
      t.text :IAMUGU
      t.text :IASUGM
      t.text :IASUGF
      t.text :IASUGU
      t.text :IHIUGM
      t.text :IHIUGF
      t.text :IHIUGU
      t.text :IBLUGM
      t.text :IBLUGF
      t.text :IBLUGU
      t.text :IWHUGM
      t.text :IWHUGF
      t.text :IWHUGU
      t.text :IMEMB
      t.text :IAM
      t.text :IAMALM
      t.text :IAMALF
      t.text :IAMALU
      t.text :IASIAN
      t.text :IASALM
      t.text :IASALF
      t.text :IASALU
      t.text :IHISP
      t.text :IHIALM
      t.text :IHIALF
      t.text :IHIALU
      t.text :IBLACK
      t.text :IBLALM
      t.text :IBLALF
      t.text :IBLALU
      t.text :IWHITE
      t.text :IWHALM
      t.text :IWHALF
      t.text :IWHALU
      t.text :IETH
      t.text :IPUTCH
      t.text :ITOTGR
    end
  end

  def self.down
    drop_table :nces06_districts
    drop_table :nces06_schools
  end

end
