require 'yaml'
YAML::ENGINE.yamler= 'psych' if defined?(YAML::ENGINE)

source 'http://rubygems.org'

#### COMMON
# source 'https://gems.railslts.com' do
  gem 'rails', '4.0.13'
  # TODO: remove pinned versions of following block when done with upgrade
  gem 'actionmailer',     '4.0.13', :require => false
  gem 'actionpack',       '4.0.13', :require => false
  gem 'activemodel',      '4.0.13', :require => false
  gem 'activerecord',     '4.0.13', :require => false
  # gem 'activeresource',   '4.0.13', :require => false
  gem 'activesupport',    '4.0.13', :require => false
  gem 'railties',         '4.0.13', :require => false
  # gem 'railslts-version', '4.0.13', :require => false
# end

gem 'activerecord-deprecated_finders'
gem 'activerecord-import'   # RAILS-4-SPIKE GEMFILE: "0.28.2"
gem "activerecord-session_store"
gem 'acts-as-taggable-on', '~> 2.4.1'
gem 'acts_as_list', '~> 0.1.6'
gem 'arrayfields'
# this is the old version of aws and is needed by our old version of paperclip
# we cannot upgrade paperclip until we have rails up to version 4.
# This uses the AWS namespace.
gem 'aws-sdk-v1'
# This is the new version of the aws sdk. It uses the Aws namespace.
# it is currently used by a rake task to archive old portals
gem 'aws-sdk',              '~> 3'
# currently (2017-06-13) axlsx requires an older version of rubyzip,
# hopefully this will shortly be remedied
gem 'axlsx',                '> 2.5'
gem 'coffee-rails',         "~> 4.0.0" # if running rails 3.1 or greater
# gem 'compass-blueprint'
# gem 'compass-rails'
# was sub-dependency of react-rails, needed in test setup code
gem 'connection_pool'
gem 'daemons', '~> 1.1.8'
gem 'default_value_for', '~> 2.0.3'
gem 'delayed_job', '~> 4.1.1'
gem 'delayed_job_active_record', '~> 4.1.0'
gem 'delayed_job_web'
gem 'devise', '~>3.1.0'
gem 'devise-encryptable'
gem 'dynamic_form', '~> 1.1.4'
gem 'exception_notification', '~> 2.5.2'
gem 'font-awesome-rails'
gem 'grit', '~> 2.4'
gem 'haml', '~> 4.0'
gem 'httparty'
gem 'in_place_editing', git: 'https://github.com/concord-consortium/in_place_editing.git'
gem 'json', '~> 1.8.6'
gem 'jwt'
gem 'jquery-fileupload-rails'
gem 'mysql2', '~> 0.3.16', platforms: [:ruby, :mingw]
gem 'nested_form'
gem 'net-sftp', '~> 2.0', require: 'net/sftp'
gem 'newrelic_rpm', '~> 4.4', '>= 4.4.0.336'
gem 'nokogiri', '~> 1.8.0'
gem 'oj', '~> 2.12.14'
gem 'omniauth'
gem 'omniauth-google-oauth2' # For google login integration.
gem 'omniauth-oauth' # For schoology integration.
gem 'open4',                '~> 1.0'
gem 'paperclip'
gem 'prawn',                '~> 0.12.0'
gem 'prawn_rails',          '~> 0.0.6'
gem 'protected_attributes'
gem 'pundit'
# cors is allowed for all groups because cors is always enabled for the interactives/export_model_library
gem 'rack-cors', require: 'rack/cors'
gem 'rack-secure_samesite_cookies',
  git: 'https://github.com/concord-consortium/secure-samesite-cookies.git',
  tag: 'v1.0.2'
gem "rails-observers"
gem 'rdoc',                 '~> 3.9.4'
gem 'redcarpet',            '~> 2.1.1'
gem 'RedCloth',             '~> 4.2.8'
gem 'rollbar'
gem 'rubyzip',              '~> 1.2.2'
gem 'rush',                 git: 'https://github.com/concord-consortium/rush.git'
gem 'sanitize'
gem 'sass',                 '~> 3.4.0'
gem 'sass-rails' # if running rails 3.1 or greater
# gem 'strong_parameters'  # RAILS-4-SPIKE GEMFILE REMOVE as part of rails 4.0 upgrade
gem 'sunspot_rails'
gem 'sunspot_solr' # optional pre-packaged Solr distribution
gem 'syntax',               '~> 1.0'
gem 'test-unit',            '~> 3.0'
gem 'tinymce-rails',        '~>3.5.6'  # RAILS-4-SPIKE GEMFILE version NOT pinned
# gem 'turbo-sprockets-rails4'
gem 'sprockets-rails', :require => 'sprockets/railtie'
# this customization is so the digests or fingerprints are correctly added to
# the assets even when they are from a theme.
gem 'themes_on_rails'

gem 'uglifier'
gem 'useragent' # detect browser types
gem 'uuidtools',            '~> 2.1.2'
gem 'virtus',               '~>1.0.3'
gem 'will_paginate',        '~> 3.0.0'
gem 'yui-compressor'

# see above; for production asset compilation.
# as per http://guides.rubyonrails.org/asset_pipeline.html#precompiling-assets
# when compressing assets without a javascript runtime:
group :production do
  gem 'therubyracer',         '~>0.12.1'
  gem 'unicorn'
end

# Feature enabling groups
group :genigames_data do
  gem 'genigames_connector', git: 'https://github.com/concord-consortium/genigames-connector.git', branch: 'spike-rails4-support'
  # gem 'genigames_connector', path: '../genigames-connector'
end
group :geniverse_backend do
  gem 'geniverse_portal_integration', git: 'https://github.com/concord-consortium/geniverse-portal-integration.git', branch: 'spike-rails4-support'
end
group :geniverse_remote_auth do
  gem 'cc_portal_remote_auth', git: 'https://github.com/concord-consortium/cc_portal_remote_auth.git', branch: 'spike-rails4-support'
end
group :geniverse_wordpress do
  gem 'cc_portal_wordpress_integration', git: 'https://github.com/concord-consortium/cc_portal_wordpress_integration.git', branch: 'spikes-rails4-support'
end


group :development do
  gem 'awesome_print'
  gem 'better_errors', '~> 1.1.0'
  gem 'bullet'
  gem 'debugger-ruby_core_source', '~> 1.3.8', platforms: [:mri_19]
  gem 'hirb'
  gem 'interactive_editor'
  gem 'lol_dba'
  gem 'rack-mini-profiler'
  gem 'rake', '~> 0.9.2'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'ruby-debug', platforms: [:mri_18, :mingw_18]
  gem 'ruby-prof'
  gem 'sextant' # adds http://localhost:9000/rails/routes in dev mode
  gem 'spring', '~> 1.7.2'
  gem 'what_methods'
  gem 'wirble'
  # gem 'xray-rails', '~> 0.1.18' # shows rendered views in browser w cmd+shift+x
end

group :test, :cucumber do
  gem 'capybara'
  gem 'capybara-mechanize'
  gem 'capybara-screenshot'
  gem 'ci_reporter'
  gem 'cucumber'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'delorean'
  gem 'email_spec'
  gem 'json-schema'
  gem 'rspec'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'spring-commands-cucumber'
  gem 'spring-commands-rspec'
  gem 'webdrivers', '~> 3.0'
  gem 'webmock', require: false
end

group :test, :cucumber, :development do
  # this is included in development so the mock data can be loaded in dev db
  gem 'factory_bot'
  gem 'guard'
  gem 'guard-cucumber'
  gem 'guard-rspec'
  gem 'highline'
  gem 'launchy'
  gem 'pry'
  gem 'pry-byebug'
  gem 'remarkable_activerecord', '~> 3.1.13', require: nil
  gem 'simplecov', require: false
end
